# Generated by Django 5.1.4 on 2025-01-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["user", "date", "name"]},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("user", "date", "name")},
        ),
    ]
